//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApplication.AuthServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthServiceReference.AuthWebServiceSoap")]
    public interface AuthWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getRole(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRole", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getRoleAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getUserName(string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getUserNameAsync(string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getUserId(string userName, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getUserIdAsync(string userName, string table);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthWebServiceSoapChannel : ClientWebApplication.AuthServiceReference.AuthWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthWebServiceSoapClient : System.ServiceModel.ClientBase<ClientWebApplication.AuthServiceReference.AuthWebServiceSoap>, ClientWebApplication.AuthServiceReference.AuthWebServiceSoap {
        
        public AuthWebServiceSoapClient() {
        }
        
        public AuthWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public string getRole(string username) {
            return base.Channel.getRole(username);
        }
        
        public System.Threading.Tasks.Task<string> getRoleAsync(string username) {
            return base.Channel.getRoleAsync(username);
        }
        
        public System.Data.DataSet getUserName(string table) {
            return base.Channel.getUserName(table);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getUserNameAsync(string table) {
            return base.Channel.getUserNameAsync(table);
        }
        
        public string getUserId(string userName, string table) {
            return base.Channel.getUserId(userName, table);
        }
        
        public System.Threading.Tasks.Task<string> getUserIdAsync(string userName, string table) {
            return base.Channel.getUserIdAsync(userName, table);
        }
    }
}
